/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ps5-controller.gltf 
Author: AHarmlessPotato (https://sketchfab.com/AHarmlessPotato)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/playstation-5-dualsense-878c1f882808477ab81c2fe86d5a3936
Title: Playstation 5 Dualsense
*/
"use client";

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { degreesToRadians } from '@/lib/inputMapper';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ps5-controller.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[degreesToRadians(-90), degreesToRadians(0), degreesToRadians(0)]} scale={props.scaleFactor}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['1011']} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['1001']} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials['1002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ps5-controller.gltf')
