/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ps5-cyberpunk.gltf --transform 
Files: ps5-cyberpunk.gltf [13.69KB] > C:\Everything\Projects\online-controller-tester\public\ps5-cyberpunk-transformed.glb [2.06MB] (-14918%)
Author: Oxicid (https://sketchfab.com/Oxicid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sony-playstation-5-dualsense-e62786c6c9514765af059b7d8ca4e648
Title: Sony PlayStation 5 DualSense
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { degreesToRadians } from '@/lib/inputMapper';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ps5-cyberpunk-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[degreesToRadians(180), degreesToRadians(0), degreesToRadians(0)]} scale={props.scaleFactor * 5}>
        <group rotation={[Math.PI / 2, 0, 0]}>
      <mesh geometry={nodes.DualSense_DualSense_Cyberpunk_0.geometry} material={materials.DualSense_Cyberpunk} />
      <mesh geometry={nodes.DualSense_DualSense_Glass_0.geometry} material={materials.DualSense_Glass} />
      </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ps5-cyberpunk-transformed.glb')
